name: end2end
channels:
- conda-forge
- pytorch
dependencies:
- python=3.8
- pytorch=1.7.0
- torchvision=0.8.0
- torchaudio=0.7.0
- cudatoolkit=10.1
- tensorboard=2.3.0
- pillow
- tqdm
- scikit-image
- scikit-learn
- imageio
- efficientnet-pytorch
- pandas
- seaborn
- albumentations=0.5.2
- scipy
- numpy=1.23.4
- imgaug
- nb_conda_kernels
- torchmetrics
- pip:
  - efficientnet_lite_pytorch
  - efficientnet_lite0_pytorch_model
